// UI-only fixtures. All real network requests are blocked by the entrypoint.
export * from "../../src/dastakV1";
import { id, read, timestamp as at } from "./fixture";
export const access = { role: "SUPERADMIN", canManageAdmins: true, slots: [
  { slot: 0, role: "SUPERADMIN", email: "owner@example.test", linked: true, version: 1 },
  { slot: 1, role: "EXECUTIVE_ADMIN", email: "operator@example.test", linked: true, version: 3 },
  { slot: 2, role: "EXECUTIVE_ADMIN", linked: false, version: 1 },
] };
export const getV1AdminAccess = () => read(access);
export const getV1AdminCommandCenter = () => read({ observedAt: at,
  actionQueue: { merchantApplications: 1, deliveryApplications: 1, openIncidents: 2, riderEscalations: 0, activePauses: 1 },
  identities: { activeAccounts: 420, customers: 380, merchants: 24, deliveryPartners: 16, deletedPersonas: 1, recoveryEligiblePhones: 1 },
  commerce: { activeOrders: 12, awaitingPayment: 2, preparingFulfilments: 6, readyFulfilments: 4, activeMissions: 3, deliveredToday: 25 },
  network: { activeOrganizations: 18, activeBranches: 24, onlineRiders: 8, assignedRiders: 3 },
  catalogue: { total: 3200, active: 3000, draft: 200, needsReview: 18, missingPrimaryImage: 3 },
});
const merchant = { organization: { id: id(1), displayName: "The Market Kitchen", legalName: "Market Kitchen Private Limited", merchantType: "RESTAURANT_CAFE", status: "ACTIVE", version: 4, activeNonTerminalFulfilmentCount: 0, activePickupReturnWorkCount: 0 },
  branch: { id: id(2), displayName: "Central Market · Restaurant & Cafe", status: "ACTIVE", version: 7, normalizedAddress: { line1: "128 Market Street", line2: "First floor, opposite the central market", city: "Vaniyambadi", state: "Tamil Nadu", postalCode: "635751", countryCode: "IN" }, latitude: 12.67, longitude: 78.61, serviceZone: { id: id(3), name: "Vaniyambadi Central" }, capacityLimit: 5, operationalState: { isOpen: false, acceptingOrders: false, version: 2 }, activeNonTerminalFulfilmentCount: 0, activePickupReturnWorkCount: 0 }, updatedAt: at };
export const getV1AdminMerchantGovernancePage = () => read({ merchants: [merchant, { ...merchant, organization: { ...merchant.organization, id: id(4), displayName: "Neighborhood Groceries", activeNonTerminalFulfilmentCount: 2 }, branch: { ...merchant.branch, id: id(5), displayName: "East branch", activeNonTerminalFulfilmentCount: 2, activePickupReturnWorkCount: 1 } }], serviceZones: [{ id: id(3), name: "Vaniyambadi Central" }], hasMore: false }, { merchants: [], serviceZones: [], hasMore: false });
const rider = { rider: { accountId: id(10), displayName: "Reviewed Test Rider", maskedPhoneNumber: "•••• 0123", accountState: "ACTIVE" }, approval: { applicationId: id(11), status: "APPROVED", submittedAt: at, reviewedAt: at, verificationVersion: 1, hasIdentityEvidence: true, hasVehicleEvidence: true }, transportMethod: "MOTORBIKE", governance: { status: "ACTIVE", version: 3 }, availability: { status: "OFFLINE", version: 8, lastSeenAt: at, serviceZone: { id: id(3), name: "Vaniyambadi Central" } }, updatedAt: at };
export const getV1AdminDeliveryPartnerGovernancePage = () => read({ deliveryPartners: [rider, { ...rider, rider: { ...rider.rider, accountId: id(12), displayName: "Rider with active custody" }, activeWork: { domain: "RETURN", id: id(13) } }], hasMore: false }, { deliveryPartners: [], hasMore: false });
export const getV1AdminCustomerRecoveryPage = () => read({ customers: [{ account: { accountId: id(20), displayName: "Reviewed Test Customer", currentPhoneNumber: "+919876540123", maskedPhoneNumber: "•••• 0123", email: "customer@example.test", accountState: "ACTIVE", customerState: "ACTIVE", createdAt: at }, phoneClaim: { version: 4, state: "CLAIMED", verificationSource: "SELF_DECLARED" }, identityProviders: ["apple"], activeSessionCount: 2, sessions: [1,2].map((n) => ({ sessionId: id(20+n), deviceName: n === 1 ? "iPhone Safari" : "Desktop browser", platform: "web", appName: "Dastak Customer", createdAt: at, lastSeenAt: at })), updatedAt: at }], hasMore: false }, { customers: [], hasMore: false });
export const getV1AdminAuditHistory = () => read({ events: [
  { source: "V1", eventId: id(31), occurredAt: at, actor: { id: id(30), displayName: "Operations reviewer" }, action: "MERCHANT_BRANCH_DETAILS_CORRECTED", resource: { type: "MERCHANT_BRANCH", id: id(2) }, reason: "Merchant-reported correction — reviewed address against the approved branch record.", summary: { previous_version: 6, resulting_version: 7, changed_fields: "display_name, normalized_address" }, references: { branchId: id(2) } },
  { source: "V1", eventId: id(32), occurredAt: at, actor: { id: id(30), displayName: "Operations reviewer" }, action: "ADMIN_ACCOUNT_SESSIONS_REVOKED", resource: { type: "ACCOUNT", id: id(20) }, reason: "Customer-reported lost device", summary: { scope: "ONE", session_count: 1 }, references: { accountId: id(20) } },
], hasMore: false }, { events: [], hasMore: false });
export const getV1AdminNetworkPage = () => read({ people: [], hasMore: false });
const department = { id: id(40), name: "Everyday essentials", slug: "essentials", status: "ACTIVE", version: 1, updatedAt: at, sortOrder: 1, navigationSection: { key: "daily", name: "Daily essentials", sortOrder: 1 } };
const category = { ...department, id: id(41), name: "Pantry", slug: "pantry", categoryTypeId: id(40) };
const subcategory = { ...category, id: id(42), categoryId: id(41), name: "Breakfast", slug: "breakfast" };
export const getV1AdminCatalogue = () => read({ categoryTypes: [department], categories: [category], subcategories: [subcategory], brands: [], skus: [], skuCount: 2, truncated: false, configuration: [{ key: "catalogue_enabled", value: true, explicit: true, valid: true, required: true }], branches: [] });
const sku = { id: id(43), categoryId: id(41), subcategoryId: id(42), categoryTypeId: id(40), categoryTypeName: department.name, categoryName: category.name, subcategoryName: subcategory.name, name: "Wholegrain breakfast oats with roasted almonds and naturally dried fruit — family value pack", canonicalName: "Wholegrain breakfast oats", slug: "fixture-oats", packSize: "500 g × 2", variant: "Roasted almond & naturally dried fruit, resealable family pack", listPricePaise: 40000, sellingPricePaise: 37500, currencyCode: "INR", taxRateBps: 500, status: "ACTIVE", selectionCount: 2, version: 4, updatedAt: at, qaStatus: "VERIFIED", activationReady: true, activationBlockers: [], imageCount: 2, aliasCount: 1, identifierCount: 1, dietType: "VEGETARIAN", attributes: {}, logisticsAttributes: {}, identifiers: [], aliases: [] };
export const getV1AdminCataloguePage = () => read({ skus: [sku, { ...sku, id: id(44), name: "Single origin filter coffee", packSize: "250 g", variant: "Medium roast", status: "DRAFT", qaStatus: "NEEDS_REVIEW", activationReady: false }], hasMore: false }, { skus: [], hasMore: false });
export const getV1AdminCatalogueAssets = () => read({ sku: { ...sku, assetVersion: 3 }, assets: [1,2].map((n) => ({ id: id(50+n), skuId: sku.id, imageKey: "fixture.svg", role: n===1 ? "PRIMARY" : "GALLERY", sortOrder: n, sourceType: "MANUFACTURER", hasSourceReference: true, widthPixels: 800, heightPixels: 800, mimeType: "image/png", status: "VERIFIED", rightsStatus: "CLEARED", version: 1, createdAt: at, storageManaged: true, canRemove: n !== 1 })) });
export const getV1AdminOperationalSafety = () => read({ permissions: { canManageOperationalPauses: true, canManageRiderEscalations: true }, pauses: [], riderEscalations: [] });
export const getV1AdminSystemHealth = () => read({ healthy: false, observedAt: at, workerConfigured: true, openCriticalIncidentCount: 1, outbox: { pending: 3, oldestPendingSeconds: 12, staleThresholdSeconds: 120, deadLetter: 0 }, notifications: { pending: 2, inFlight: 1, deadLetter: 0 }, paymentReconciliationOpen: 0, operationalAlerts: { counts: { riderEscalationOpenCount: 0, merchantUnreachableBranchCount: 1, customerUnreachableDueCount: 0 }, thresholds: { riderEscalationOpenCount: 2, merchantUnreachableBranchCount: 2, customerUnreachableDueCount: 2 } }, lastMonitorRun: { completedAt: at, findingCount: 1 }, incidents: [{ id: id(60), invariantKey: "FIXTURE_REVIEW_SIGNAL", entityType: "TEST_ORDER", entityId: id(61), lastDetectedAt: at, occurrenceCount: 1 }] });
export const getV1AdminExecutionOrders = () => read({ orders: [], hasMore: false });
