-- Owner-curated milk powders and creamers for Amul and Nestle.
do $$
declare a constant uuid := '7105206a-6fec-45c9-8c00-3dfd5178fc1b'; b uuid; c uuid; s uuid; batch uuid := gen_random_uuid(); r record;
begin
 insert into dastak_v1.catalogue_import_batches(id,source_type,source_name,source_reference,status,counts,created_by,completed_at) values(batch,'OWNER_CURATED','Amul and Nestle milk powders and creamers','dastak://catalogue/dairy-bread-eggs/milk-powders-creamers-2026-09-18','COMPLETED',jsonb_build_object('brands',2,'skus',11),a,now());
 for r in select * from (values
 ('Amul','amul','milk-powder','Amulya Dairy Whitener','amulya-dairy-whitener-200','200 g','104','amul'),('Amul','amul','milk-powder','Amulya Dairy Whitener','amulya-dairy-whitener-500','500 g','255','amul'),('Amul','amul','milk-powder','Amulya Dairy Whitener','amulya-dairy-whitener-1kg','1 kg','495','amul'),('Amul','amul','milk-powder','Amul Whole Milk Powder','amul-whole-milk-powder-450','450 g','280','amul'),('Amul','amul','milk-powder','Amul Whole Milk Powder','amul-whole-milk-powder-500','500 g','270','amul'),('Amul','amul','milk-powder','Sagar Skimmed Milk Powder','sagar-skimmed-milk-powder-500','500 g','220','amul'),('Nestle','nestle','milk-powder','Nestle Everyday Dairy Whitener','nestle-everyday-dairy-whitener-200','200 g','128','nestle'),('Nestle','nestle','milk-powder','Nestle Everyday Dairy Whitener','nestle-everyday-dairy-whitener-400','400 g','255','nestle'),('Nestle','nestle','milk-powder','Nestle Everyday Dairy Whitener','nestle-everyday-dairy-whitener-1kg','1 kg','625','nestle'),('Nestle','nestle','dairy-creamer','Nestle Coffee-mate Coffee Creamer','nestle-coffee-mate-creamer-200','200 g','399','nestle'),('Nestle','nestle','dairy-creamer','Nestle Coffee-mate Coffee Creamer','nestle-coffee-mate-creamer-425','425.2 g','829','nestle')) x(brand,brand_slug,subcat,name,slug,pack,price,prefix) loop
  insert into dastak_v1.brands(name,slug,status,created_by) values(r.brand,r.brand_slug,'ACTIVE',a) on conflict(slug) do update set status='ACTIVE',updated_at=now(); select id into b from dastak_v1.brands where slug=r.brand_slug;
  select sc.id into c from dastak_v1.subcategories sc join dastak_v1.categories ca on ca.id=sc.category_id join dastak_v1.category_types ct on ct.id=ca.category_type_id where ct.slug='dairy-bread-eggs' and sc.slug=r.subcat; if c is null then raise exception 'missing milk powder subcategory %',r.subcat; end if;
  insert into dastak_v1.skus(subcategory_id,brand_id,canonical_name,slug,pack_size,description,image_key,list_price_paise,selling_price_paise,currency_code,tax_rate_bps,logistics_attributes,status,created_by,product_kind,quantity_value,quantity_unit,country_of_origin_code,diet_type,qa_status) values(c,b,r.name,r.slug,r.pack,'Branded '||r.name||' for Dastak delivery.','canonical/staging/milk-powders-creamers/'||r.prefix||'-'||r.slug||'.'||case when r.prefix='amul' then 'png' else 'jpg' end,(r.price::numeric*100)::bigint,(r.price::numeric*100)::bigint,'INR',0,jsonb_build_object('temperatureClass','AMBIENT'),'DRAFT',a,'PACKAGED',regexp_replace(r.pack,'[^0-9.]','','g')::numeric,case when r.pack like '%kg' then 'kg' else 'g' end,'IN','VEG','PENDING') on conflict(slug) do update set subcategory_id=excluded.subcategory_id,brand_id=excluded.brand_id,canonical_name=excluded.canonical_name,pack_size=excluded.pack_size,image_key=excluded.image_key,list_price_paise=excluded.list_price_paise,selling_price_paise=excluded.selling_price_paise,updated_at=now(),version=dastak_v1.skus.version+1 returning id into s;
  insert into dastak_v1.sku_images(sku_id,image_key,role,sort_order,source_type,source_reference,mime_type,status,created_by,verified_by,verified_at,rights_status,rights_reference,rights_verified_by,rights_verified_at) values(s,'canonical/staging/milk-powders-creamers/'||r.prefix||'-'||r.slug||'.'||case when r.prefix='amul' then 'png' else 'jpg' end,'PRIMARY',0,'OWNER_CAPTURE','owner-curated branded milk powder artwork sourced from manufacturer or retailer product listing',case when r.prefix='amul' then 'image/png' else 'image/jpeg' end,'VERIFIED',a,a,now(),'CLEARED','owner-authorised catalogue artwork',a,now()) on conflict(sku_id) where role='PRIMARY' do update set image_key=excluded.image_key,status='VERIFIED',verified_by=a,verified_at=now(),rights_status='CLEARED',rights_verified_by=a,rights_verified_at=now(),version=dastak_v1.sku_images.version+1;
  update dastak_v1.skus set status='ACTIVE',qa_status='VERIFIED',qa_verified_by=a,qa_verified_at=now(),updated_at=now(),version=version+1 where id=s;
 end loop;
end; $$;
